export const pens:any = {
  unknown: '#b3b3b3',
  gene: '#66ffb3',
  mRNA: '#99b3ff',
  CDS: '#66ffb3',
  intron: '#ab6dcf',
  rRNA: '#99b3ff',
  ncRNA: '#99b3ff',
  centromere_DNA_Element_I: '#b5cf6d',
  transposable_element_gene: '#66ffb3',
  centromere_DNA_Element_II: '#b5cf6d',
  external_transcribed_spacer_region: '#cccccc',
  five_prime_UTR_intron: '#ab6dcf',
  LTR_retrotransposon:'#6257ff',
  centromere:'#aaaaaa',
  centromere_DNA_Element_III:'#b5cf6d',
  pseudogene:'#66ffb3',
  snRNA:'#99b3ff',
  telomere:'#97d7f7',
  long_terminal_repeat:'#97d7f7',
  exon:'#97d7f7',
  ARS:'#97d7f7',
  tRNA:'#99b3ff',
  internal_transcribed_spacer_region:'#97d7f7',
  plus_1_translational_frameshift:'#97d7f7',
  snoRNA:'#99b3ff',
}

export default (type: string):string => pens[type as any] || '#eee';